In [1]:
import numpy as np

Arrays can be created by a list, or a list of lists

In [2]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [list1,list2]

In [3]:
np.array(list1)

array([1, 2, 3])

In [4]:
np.array(list3)

array([[1, 2, 3],
       [4, 5, 6]])

## Methods 1


**arange**- Generate an array that's evenly spaced between the first and last element
**linspace** - Linearly spaced array from the first element to the last with designated *number of steps*

In [10]:
# Default step is 1
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Declare the step as every 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [23]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

## Methods 2

These can be used to create 1-d or 2-d matrixes

**zeros** - zeros matrix
**ones** - ones matrix
**random.rand** - random matrix from *uniform* distribution
**random.randn** - random matrix from standard normal distribution


In [12]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.ones((1,3))

array([[1., 1., 1.]])

In [18]:
np.random.rand(4)

array([0.21165156, 0.95636178, 0.50129022, 0.82455806])

In [21]:
# Note the lack of the second braces
np.random.randn(4,5)

array([[-1.01848804,  0.83481384, -0.96937228,  1.66424553, -0.26819527],
       [ 0.84123728,  0.32869369, -1.64326435,  0.39896216,  0.9008502 ],
       [ 1.1033326 ,  0.39693099,  0.21162448, -0.5761868 ,  1.63130718],
       [-1.65372228,  0.90770303,  1.754873  ,  1.46229116,  0.05727983]])